# Generated by Django 3.2.9 on 2021-12-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100)),
                ('courseTime', models.CharField(max_length=50)),
                ('instructorName', models.CharField(max_length=50)),
                ('taName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100)),
                ('labNum', models.IntegerField()),
                ('labTime', models.CharField(max_length=50)),
                ('taName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=25)),
                ('password1', models.CharField(max_length=25)),
                ('password2', models.CharField(max_length=25)),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CourseAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName' , models.CharField(max_length=100)),
                ('assignmentNum' , models.IntegerField()),
                ( 'assignment' ,models.CharField(max_length=50)),
                ( 'assignment1' , models.CharField(max_length=50)),
            ],
        ),
    ]
