# Generated by Django 3.2.9 on 2021-12-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='courseDay',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='courses',
            name='courseTime',
            field=models.DateTimeField(),
        ),
    ]
