# Generated by Django 3.2.9 on 2021-12-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_apps', '0003_alter_courses_coursetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='courseNum',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
