# Generated by Django 3.2.9 on 2021-12-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_apps', '0005_users_phonenum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='instructorName',
            new_name='instructorFirstName',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='taName',
            new_name='instructorLastName',
        ),
        migrations.RenameField(
            model_name='labs',
            old_name='courseName',
            new_name='courseNum',
        ),
        migrations.RenameField(
            model_name='labs',
            old_name='taName',
            new_name='taFirstName',
        ),
        migrations.AddField(
            model_name='courses',
            name='taFirstName',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='taLastName',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labs',
            name='taLastName',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
