# Generated by Django 3.2.9 on 2021-12-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_apps', '0005_users_phonenum'),
    ]

    operations = [
        migrations.CreateModel(
            name='createAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createNewAccount', models.CharField(max_length=100)),
                ('createUser', models.IntegerField()),
                ('createPassword', models.CharField(max_length=50)),
                ('generateID', models.CharField(max_length=50)),
            ],
        ),
    ]
