# Generated by Django 3.2.9 on 2021-12-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_apps', '0006_auto_20211217_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password2',
        ),
    ]
